openapi: 3.0.3
info:
  title: service API
  description: service API
  contact:
    name: Sujata
  version: 1.0.0
servers:
  - url: http://localhost:8090
    description: Inferred Url
tags:
  - name: status-controller
    description: Status Controller
paths:
  /api/status:
    post:
      tags:
        - status-controller
      summary: saveStatus
      operationId: saveStatusUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusDetails'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StatusDetails'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/status/{id}:
    get:
      tags:
        - status-controller
      summary: getStatusById
      operationId: getByIdUsingGET
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StatusDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    StatusDetails:
      title: StatusDetails
      type: object
      properties:
        arrival:
          type: string
        arrivalDate:
          type: string
        departure:
          type: string
        departureDate:
          type: string
        email:
          type: string
        firstName:
          type: string
        id:
          type: integer
          format: int32
        lastName:
          type: string